### ISSUE TITLE
JsonException trying to access `LocalDocker.volumes()` 

### ISSUE THREAD

**Issue by sbespalov** [amihaiemil/docker-java-api#241]
Probably something wrong with expected JSON format.

How to reproduce:
```
	Volumes volumes = new LocalDocker(Paths.get("/var/run/docker.sock").toFile()).volumes();
	volumes.iterator();
```
Expected result:
Got the volumes iterator

Actual result:
` javax.json.JsonException` 
```
Exception in thread "main" javax.json.JsonException: Cannot read JSON array, found JSON object
	at org.glassfish.json.JsonReaderImpl.readArray(JsonReaderImpl.java:122)
	at com.amihaiemil.docker.ReadJsonArray.handleResponse(ReadJsonArray.java:61)
	at com.amihaiemil.docker.ReadJsonArray.handleResponse(ReadJsonArray.java:1)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.amihaiemil.docker.HttpClientEnvelope.execute(HttpClientEnvelope.java:103)
	at com.amihaiemil.docker.ResourcesIterator.<init>(ResourcesIterator.java:64)
	at com.amihaiemil.docker.ListedVolumes.iterator(ListedVolumes.java:78)
	at Main.main(Main.java:11)
```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@sbespalov Right, turns out that List-Volumes operation returns a JsonObject, not a JsonArray:

https://docs.docker.com/engine/api/v1.30/#operation/VolumeList

The format is actually:

```json
{
    "Volumes": [
        {}
     ],
    "Warnings": [ ]
}
```

Let's parse the response and iterate the ``Volumes`` array, ignore the ``Warnings`` for now.

**Comment by 0crat** [comment]
Job [#241](https://github.com/amihaiemil/docker-java-api/issues/241) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sbespalov[/z](https://www.0crat.com/u/sbespalov)

**Comment by 0crat** [comment]
The job [#241](https://github.com/amihaiemil/docker-java-api/issues/241) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/b644d66d-b3ab-45e4-8fd8-f422de3633eb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@sbespalov Merged, please close

**Comment by 0crat** [comment]
The job [#241](https://github.com/amihaiemil/docker-java-api/issues/241) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
