### ISSUE TITLE
Exception while trying to use Logs.fetch() with docker 18.09

### ISSUE THREAD

**Issue by nmaguiar** [amihaiemil/docker-java-api#256]
Using release 0.0.6 in a container, with docker 18.09, fails whenever trying to use the logs().fetch() method for another container with the following exception:

````
com.amihaiemil.docker.UnexpectedResponseException: Expected status 200 but got 400 when calling unix://localhost:80/v1.35/containers/a589995677a2511cd8db4a72e79e04d1b33467f27cf951896f3129f22dca88c4/logs. Response body was {"message":"Bad parameters: you must choose at least one stream"}
        at com.amihaiemil.docker.MatchStatus.handleResponse(MatchStatus.java:66)
        at com.amihaiemil.docker.MatchStatus.handleResponse(MatchStatus.java:39)
        at com.amihaiemil.docker.ReadString.handleResponse(ReadString.java:57)
        at com.amihaiemil.docker.ReadString.handleResponse(ReadString.java:39)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at com.amihaiemil.docker.HttpClientEnvelope.execute(HttpClientEnvelope.java:103)
        at com.amihaiemil.docker.RtLogs.fetch(RtLogs.java:84)
[...]
````
From what I understood from "Bad parameters: you must choose at least one stream", it looks like it's necessary to specify if its stdout or stderr since both, by default, are false.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@nmaguiar[/z](https://www.0crat.com/u/nmaguiar) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@nmaguiar thanks, definetely a bug. And many thanks for the donation, much appreciated.

We'll fix it asap. In the meantime, try to use [this](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/LocalDocker.java#L65) ctor, perhaps you can use the API version 1.39? Long shot, but maybe it works.

**Comment by 0crat** [comment]
Thanks for your contribution, @nmaguiar[/z](https://www.0crat.com/u/nmaguiar)! If you would be a member of [the project](https://www.0crat.com/p/G6LPQQV2P), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#256](https://github.com/amihaiemil/docker-java-api/issues/256) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/5c3bde95-3136-4e03-8944-34a765e8ed4a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#256` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by nmaguiar** [comment]
> @nmaguiar thanks, definetely a bug. And many thanks for the donation, much appreciated.
> 
> We'll fix it asap. In the meantime, try to use [this](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/LocalDocker.java#L65) ctor, perhaps you can use the API version 1.39? Long shot, but maybe it works.

Thank you. Just tried with v1.39 but, unfortunately, got the same exception.

**Comment by amihaiemil** [comment]
@nmaguiar fixed. For now, it'll read both stdout and sterr, there is a puzzle to make that customizable. Version 0.0.7 released, you should be able to take it from Maven Central already. 

Can you close this? If I do it, I think the PM will complain :D

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#256](https://github.com/amihaiemil/docker-java-api/issues/256) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
